# Generated by Django 4.2.27 on 2026-08-23 12:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DailyJournal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("summary", models.TextField()),
                (
                    "total_pnl",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("win_rate", models.FloatField(default=0.0)),
                ("trades_count", models.IntegerField(default=0)),
                ("winning_trades", models.IntegerField(default=0)),
                ("losing_trades", models.IntegerField(default=0)),
                ("key_takeaways", models.JSONField(blank=True, default=list)),
                ("sent_to_alerts", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="StockSentiment",
            fields=[
                (
                    "symbol",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                (
                    "sentiment",
                    models.CharField(
                        choices=[
                            ("BULLISH", "Bullish"),
                            ("NEUTRAL", "Neutral"),
                            ("BEARISH", "Bearish"),
                        ],
                        default="NEUTRAL",
                        max_length=10,
                    ),
                ),
                ("score", models.FloatField(default=0.0)),
                ("rationale", models.TextField(blank=True)),
                ("headlines", models.JSONField(blank=True, default=list)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
    ]
