# Generated by Django 5.2.16 on 2026-07-21 05:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DailyPerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                (
                    "starting_capital",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "ending_capital",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("total_trades", models.IntegerField(default=0)),
                ("winning_trades", models.IntegerField(default=0)),
                ("losing_trades", models.IntegerField(default=0)),
                (
                    "realized_pnl",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("max_drawdown_pct", models.FloatField(default=0)),
                ("win_rate", models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("symbol", models.CharField(max_length=20, unique=True)),
                (
                    "side",
                    models.CharField(
                        choices=[("LONG", "Long"), ("SHORT", "Short")], max_length=5
                    ),
                ),
                ("quantity", models.IntegerField()),
                ("entry_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("current_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("stop_loss", models.DecimalField(decimal_places=2, max_digits=12)),
                ("take_profit", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "unrealized_pnl",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("is_open", models.BooleanField(default=True)),
                ("opened_at", models.DateTimeField(auto_now_add=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-opened_at"],
            },
        ),
        migrations.CreateModel(
            name="Signal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("symbol", models.CharField(max_length=20)),
                ("strategy", models.CharField(max_length=50)),
                (
                    "action",
                    models.CharField(
                        choices=[("BUY", "Buy"), ("SELL", "Sell"), ("HOLD", "Hold")],
                        max_length=4,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("strength", models.FloatField(default=0.0)),
                ("metadata_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TradeLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("symbol", models.CharField(max_length=20)),
                ("side", models.CharField(max_length=4)),
                ("quantity", models.IntegerField()),
                ("entry_price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "exit_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "pnl",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("pnl_pct", models.FloatField(default=0)),
                ("strategy", models.CharField(max_length=50)),
                (
                    "pnl_type",
                    models.CharField(
                        choices=[
                            ("REALIZED", "Realized"),
                            ("UNREALIZED", "Unrealized"),
                        ],
                        default="REALIZED",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("broker_order_id", models.CharField(blank=True, max_length=50)),
                ("symbol", models.CharField(max_length=20)),
                (
                    "side",
                    models.CharField(
                        choices=[("BUY", "Buy"), ("SELL", "Sell")], max_length=4
                    ),
                ),
                ("quantity", models.IntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("EXECUTED", "Executed"),
                            ("CANCELLED", "Cancelled"),
                            ("REJECTED", "Rejected"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("mode", models.CharField(default="paper", max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("executed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "signal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.signal",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
