# Generated by Django 4.2.27 on 2026-08-23 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="average_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="order",
            name="filled_quantity",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="order",
            name="rejection_reason",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PARTIALLY_FILLED", "Partially Filled"),
                    ("EXECUTED", "Executed"),
                    ("CANCELLED", "Cancelled"),
                    ("REJECTED", "Rejected"),
                    ("FAILED", "Failed"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
