# Generated by Django 4.2.27 on 2026-08-23 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_order_average_price_order_filled_quantity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="signal",
            name="explanation",
            field=models.TextField(blank=True, default=""),
        ),
    ]
