# Generated by Django 4.2.27 on 2026-08-31 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_signal_explanation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="position",
            name="symbol",
            field=models.CharField(max_length=20),
        ),
    ]
